long_reads:
    none
workdir:
    none
reference_filter:
    none
short_reads_1:
    none
short_reads_2:
    none
max_threads:
    24
max_memory:
    250
nanopore_dir:
    none
guppy_model:
    r941_min_high_g360
genome_size:
    5000000
meta_genome_size:
    50000000
fastq_pass_dir:
    none
sequence_summary:
    none
gtdbtk_folder:
    /srv/db/gtdbtk/official/release95
busco_folder:
    /srv/longreads/nanopore/busco
unassembled_long:
    none
instrain_params:
    ""
profile_read_list:
    none
pilon_memory:
    128
email:
    somename@email.co
