long_reads:
    none
workdir:
    none
reference_filter:
    none
short_reads_1:
    none
short_reads_2:
    none
max_threads:
    24
nanopore_dir:
    none
guppy_model:
    r941_flip243
genome_size:
    5000000
fastq_pass_dir:
    none
sequence_summary:
    none