long_reads:
    none
workdir:
    none
reference_filter:
    none
short_reads_1:
    none
short_reads_2:
    none
max_threads:
    24
nanopore_dir:
    none
guppy_model:
    r941_flip235
genome_size:
    5000000
meta_genome_size:
    50000000
fastq_pass_dir:
    none
sequence_summary:
    none
checkm_folder:
    /srv/db/checkm_data/1.0.0/
gtdbtk_folder:
    /srv/db/gtdbtk/official/release89
busco_folder:
    /srv/longreads/nanopore/busco
unassembled_long:
    none
profile_read_list:
    none